[package]
name = "benchmark"
version = "0.0.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
license = "MIT"
publish = false

[dependencies]
malva = { path = "../malva" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "fmt"
harness = false
