[package]
name = "malva"
version = "0.0.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "CSS/SCSS/Sass/Less formatter."
repository = "https://github.com/g-plane/malva"
license = "MIT"

[dependencies]
itertools = "0.11"
memchr = "2.6"
raffia = "0.5"
serde = { version = "1.0", optional = true }
tiny_pretty = { path = "../../tiny_pretty" }

[features]
config_serde = ["raffia/config_serde", "serde"]
