[package]
name = "malva"
version = "0.0.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "CSS/SCSS/Sass/Less formatter."
repository = "https://github.com/g-plane/malva"
license = "MIT"

[dependencies]
itertools = "0.11"
raffia = "0.4"
tiny_pretty = { path = "../../tiny_pretty" }
